name: Portfolio Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/node2/Portfolio/portfolio
            git pull origin main
            docker build -t portfolio:latest .
            docker stop portfolio_c1 || true
            docker rm portfolio_c1 || true
            docker run -d --restart always --name portfolio_c1 -p 4000:80 portfolio:latest
